//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab666.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lab666.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;line num=&quot;4&quot;&gt;
        ///    &lt;word num=&quot;0&quot;&gt;ку&lt;/word&gt;
        ///    &lt;word num=&quot;1&quot; num2=&quot;0&quot;&gt;ку&lt;/word&gt;
        ///    &lt;word num=&quot;2&quot;&gt;ку&lt;/word&gt;
        ///    &lt;word num=&quot;3&quot;&gt;ку&lt;/word&gt;
        ///    &lt;word num=&quot;4&quot; num2=&quot;0&quot;&gt;ку&lt;/word&gt;
        ///    &lt;word num=&quot;5&quot;&gt;ку&lt;/word&gt;
        ///  &lt;/line&gt;
        ///  &lt;line num=&quot;1&quot;&gt;
        ///    &lt;word num=&quot;0&quot;&gt;как&lt;/word&gt;
        ///    &lt;word num=&quot;1&quot; num2=&quot;0&quot;&gt;дела&lt;/word&gt;
        ///  &lt;/line&gt;
        ///  &lt;line num=&quot;2&quot;&gt;
        ///    &lt;word num=&quot;0&quot;&gt;тест&lt;/word&gt;
        ///    &lt;word num=&quot;1&quot; num2=&quot;0&quot;&gt;для&lt;/word&gt;
        ///    &lt;word num=&quot;2&quot; num2=&quot;0&quot;&gt;практики&lt;/word&gt;
        ///  &lt;/line&gt;
        ///  &lt;l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string num15 {
            get {
                return ResourceManager.GetString("num15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to привет
        ///как дела
        ///тест для практики
        ///132 4223
        ///ку ку ку ку ку ку.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
    }
}
